name: Signed attestation

on:
  workflow_run:
    workflows: ["Build Java JAR"]
    types:
      - completed

jobs:
  compute-hash:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: debig logging
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-app
          path: ./artifact
      - name: list artifact
        run: ls -l ./artifact
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ./artifact/my*

